---
title: "Data_Manipulation"
output: github_document
---


```{r}
library(tidyverse)
```

Let's import the datasets. 


```{r}
litters_df = 
  read_csv("data/FAS_litters.csv",na = c("NA",".",""))
litters_df = 
  janitor::clean_names(litters_df)
pups_df = 
  read_csv("data/FAS_pups.csv", skip = 3, na = c("NA",".",""))
pups_df = 
  janitor::clean_names(pups_df)
```

## `select`

`select` selects variables from my df

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

select a range

```{r}
select(litters_df, group:gd_of_birth)
```

select by removal

```{r}
select(litters_df, -group)
select(litters_df, -(group:gd_of_birth))
```

select by prefix
```{r}
select(litters_df, group, starts_with("gd"))
```

rearrange by selecting

```{r}
select(litters_df, starts_with("gd"),group)
select(litters_df,litter_number,everything())
relocate(litters_df,litter_number)
```

what if I only select one variable?

```{r}
select(litters_df,group)
pull(litters_df,group)
```

`select` selects variables from my df (pupsdf) Learning assessment code

```{r}
select(pups_df, litter_number, sex, pd_ears )
```

## `filter`

`filter` to filter out rows

```{r}
filter(litters_df,gd_of_birth==20, pups_born_alive==6)
```

look for more than five pups alive, less than equal, greater than equal, all but five

```{r}
filter(litters_df, pups_born_alive>5)
filter(litters_df, pups_born_alive<=5)
filter(litters_df, pups_born_alive>=5)
filter(litters_df, pups_born_alive!=5)
```

