---
title: "Data import"
output: github_document
---



```{r}
library(tidyverse)
library(janitor)
library(readxl)
library(haven)
```

Let's import a dataset.

```{r}
litters_df=
  read_csv("data/FAS_litters.csv")
```

Look at your data.

```{r}
names(litters_df)
```

Clean data names 

```{r}
litters_df <- 
  janitor::clean_names(litters_df)
```

sometimes skimming data is neat

```{r}
skimr::skim(litters_df)
```

## fix the missingness

```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("NA",".",""))
```

skim.

```{r}
skimr::skim(litters_df)
```

## import pups data

```{r}
pups_df = 
  read_csv(
    "data/FAS_pups.csv",
    skip=3,
    na = c("NA",".","")
    )

pups_df <- 
  janitor::clean_names(pups_df)

skimr::skim(pups_df)
```

## Okay what about excel
CSVs are great but sometimes you need an excel. 

```{r}
mlb_df=
  read_excel("data/mlb11.xlsx")
```

Import LotR

```{r}
fotr_df =
  read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```

## SAS?

Import the PULSE data

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
pulse_df <- 
  janitor::clean_names(pulse_df)
```

## why is read.csv bad? prints everything

```{r}
litters_df_base = 
  read.csv("data/FAS_litters.csv")
```


